name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "rc/*" ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: taiki-e/checkout-action@v1.4.0
      - name: install rust
      - uses: taiki-e/github-actions/install-rust@nightly
      - run: cargo t --all-features --all-targets
      - run: cargo t --doc
      - run: cargo r --example author
